apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer
  labels:
    app: nginx-loadbalancer
    env: dev
spec:
  containers:
  - name: ngix-container-loadbalancer
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 8765
    protocol: TCP
    targetPort: 80  
  selector:
    app: nginx-loadbalancer
    env: dev