apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: [fs-0d773b5c54e3afad9] 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: efs-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    volume: efs
    provision: static
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: persistent-storage-efs
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage-efs
    persistentVolumeClaim:
      claimName: efs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80  
  selector:
    volume: efs
    provision: static
