---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    volume: efs
    provision: dynamic
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: persistent-storage-dynamic-efs
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1b
  volumes:
  - name: persistent-storage-dynamic-efs
    persistentVolumeClaim:
      claimName: efs-claim-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-Dynamic
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80  
  selector:
    volume: efs
    provision: dynamic
