apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: roboshop
  labels: 
    app: nginx
    environment: dev
  spec:
  containers:
  - name: hello-pod
    image: dockerdevops1994/ultimate-cicd:6
    ports:
    - containerPort: 80