apiVersion: v1
kind: Pod
metadata:
  name: labels
  namespace: roboshop
  labels: 
    app: nginx
    environment: dev
spec:
  containers:
  - name: label
    image: nginx
    ports:
    - containerPort: 80