apiVersion: v1
kind: Pod
metadata:
  name: enivornment
  namespace: roboshop
  labels: 
    app: nginx
    environment: dev
  annotations:
    com.roboshop.training.duration: "120 hrs"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: label
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: DEMO_GREETING
      value: "hello docker"
    - name: HELLO
      value: "hello from my world"