apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-container
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: Username
      valueFrom:
        secretMapKeyRef:
          name: secret-nginx         # The ConfigMap this value comes from.
          key: username
    - name: Password
      valueFrom:
        secretMapKeyRef:
          name: secret-nginx          # The ConfigMap this value comes from.
          key: password
